// packages/svelte/demo/App.svelte
<script lang="ts">
    import type {SelectionEvent} from '@viselect/vanilla/src';
    import SelectionArea from '../src/SelectionArea.svelte';

    const range = (n: number, offset = 0) => new Array(n).fill(0).map((_, i) => offset + i);
    let selected: Set<number> = new Set();

    const extractIds = (els: Element[]): number[] =>
        els.map(v => v.getAttribute('data-key'))
            .filter(Boolean)
            .map(Number);

    const onStart = ({event, selection}: SelectionEvent) => {
        if (!event?.ctrlKey && !event?.metaKey) {
            selection.clearSelection();
            selected = new Set();
        }
    };

    const onMove = ({store: {changed: {added, removed}}}: SelectionEvent) => {
        extractIds(added).forEach(id => selected.add(id));
        extractIds(removed).forEach(id => selected.delete(id));
        selected = selected;
    };

</script>

<main>
    <h1>Svelte</h1>
    <SelectionArea className="container green"
                   onStart={onStart}
                   onMove={onMove}
                   options={{selectables: '.selectable'}}>
        {#each range(42) as id}
            <div class="{selected.has(id) ? 'selectable selected' : 'selectable'}"
                 data-key={id}></div>
        {/each}
    </SelectionArea>
    <SelectionArea className="container blue"
                   onStart={onStart}
                   onMove={onMove}
                   options={{selectables: '.selectable'}}>
        {#each range(42, 42) as id}
            <div class="{selected.has(id) ? 'selectable selected' : 'selectable'}"
                 data-key={id}></div>
        {/each}
    </SelectionArea>
    <SelectionArea className="container red"
                   onStart={onStart}
                   onMove={onMove}
                   options={{selectables: '.selectable'}}>
        {#each range(400, 84) as id}
            <div class="{selected.has(id) ? 'selectable selected' : 'selectable'}"
                 data-key={id}></div>
        {/each}
    </SelectionArea>
</main>

// packages/vue/demo/App.vue
<template>
    <h1>Vue</h1>

    <SelectionArea class="container green"
                   :options="{selectables: '.selectable'}"
                   :on-move="onMove"
                   :on-start="onStart">
        <div v-for="id of range(42)" :key="id" :data-key="id"
             class="selectable" :class="{selected: selected.has(id)}"/>
    </SelectionArea>

    <SelectionArea class="container blue"
                   :options="{selectables: '.selectable'}"
                   :on-move="onMove"
                   :on-start="onStart">
        <div v-for="id of range(42, 42)" :key="id" :data-key="id"
             class="selectable" :class="{selected: selected.has(id)}"/>
    </SelectionArea>

    <SelectionArea class="container red"
                   :options="{selectables: '.selectable'}"
                   :on-move="onMove"
                   :on-start="onStart">
        <div v-for="id of range(400, 84)" :key="id" :data-key="id"
             class="selectable" :class="{selected: selected.has(id)}"/>
    </SelectionArea>
</template>

<script lang="ts" setup>
import {SelectionEvent} from '@vanilla/types';
import {reactive} from 'vue';
import SelectionArea from '../src/SelectionArea.vue';

const selected = reactive<Set<number>>(new Set());

const extractIds = (els: Element[]): number[] => {
    return els.map(v => v.getAttribute('data-key'))
        .filter(Boolean)
        .map(Number);
};

const onStart = ({event, selection}: SelectionEvent): void => {
    if (!event?.ctrlKey && !event?.metaKey) {
        selection.clearSelection();
        selected.clear();
    }
};

const onMove = ({store: {changed: {added, removed}}}: SelectionEvent): void => {
    extractIds(added).forEach(id => selected.add(id));
    extractIds(removed).forEach(id => selected.delete(id));
};

const range = (to: number, offset = 0): number[] => {
    return new Array(to).fill(0).map((_, i) => offset + i);
};

</script>

<style>
@import './index.css';
</style>
