// packages/svelte/src/SelectionArea.svelte
<script lang="ts">
    import SelectionArea from '../../vanilla/src';
    import type {SelectionEvents, SelectionOptions} from '../../vanilla/src';
    import {onDestroy, onMount} from 'svelte';

    export let onBeforeStart: SelectionEvents['beforestart'] | null = null;
    export let onStart: SelectionEvents['start'] | null = null;
    export let onMove: SelectionEvents['move'] | null = null;
    export let onStop: SelectionEvents['stop'] | null = null;

    export let className: string;
    export let options: Partial<Omit<SelectionOptions, 'boundaries'>>;

    let container: HTMLDivElement;
    let selection: SelectionArea;

    onMount(() => {
        selection = new SelectionArea({
            boundaries: container,
            ...options
        });

        onBeforeStart && selection.on('beforestart', onBeforeStart);
        onStart && selection.on('start', onStart);
        onMove && selection.on('move', onMove);
        onStop && selection.on('stop', onStop);
    });

    onDestroy(() => selection.destroy());
</script>

<div bind:this={container} class={className}>
    <slot/>
</div>

// packages/vue/src/SelectionArea.vue
<template>
    <div ref="container">
        <slot/>
    </div>
</template>

<script lang="ts" setup>
import SelectionArea, {SelectionEvents} from '@vanilla/index';
import {SelectionOptions} from '@vanilla/types';
import {defineProps, onBeforeUnmount, ref, watchEffect} from 'vue';

const props = defineProps<{
    options: Omit<SelectionOptions, 'boundaries'>;
    onBeforeStart?: SelectionEvents['beforestart'];
    onStart?: SelectionEvents['start'];
    onMove?: SelectionEvents['move'];
    onStop?: SelectionEvents['stop'];
}>();

const container = ref<HTMLDivElement>();
let instance: SelectionArea;

watchEffect(() => {
    if (container.value) {
        instance?.destroy();

        instance = new SelectionArea({
            boundaries: container.value,
            ...props.options
        });

        const {onBeforeStart, onStart, onMove, onStop} = props;

        onBeforeStart && instance.on('beforestart', onBeforeStart as SelectionEvents['beforestart']);
        onStart && instance.on('start', onStart as SelectionEvents['start']);
        onMove && instance.on('move', onMove as SelectionEvents['move']);
        onStop && instance.on('stop', onStop as SelectionEvents['stop']);
    }
});


onBeforeUnmount(() => {
    instance?.destroy();
});
</script>
